branch-defaults:
  master:
    environment: appselma
environment-defaults:
  appselma:
    branch: null
    repository: null
global:
  application_name: AppSelMa
  default_ec2_keyname: eb-test
  default_platform: Docker 18.09.9-ce
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: milos-tdl-aws
  sc: git
  workspace_type: Application
